# Generated by Django 5.2.3 on 2025-06-16 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeaOrigin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть публикацию.",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Максимальная длина 256 символов",
                        max_length=256,
                        verbose_name="Страна происхождения",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание региона"),
                ),
            ],
            options={
                "verbose_name": "страна происхождения",
                "verbose_name_plural": "Страны происхождения",
                "ordering": ("name",),
                "abstract": False,
                "default_related_name": "%(app_label)s_%(class)s_related",
            },
        ),
        migrations.CreateModel(
            name="TeaType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть публикацию.",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Максимальная длина 256 символов",
                        max_length=256,
                        verbose_name="Название типа чая",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.",
                        unique=True,
                        verbose_name="Идентификатор",
                    ),
                ),
            ],
            options={
                "verbose_name": "тип чая",
                "verbose_name_plural": "Типы чая",
                "ordering": ("title",),
                "abstract": False,
                "default_related_name": "%(app_label)s_%(class)s_related",
            },
        ),
        migrations.CreateModel(
            name="TeaPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("green", "Зеленый"),
                            ("black", "Черный"),
                            ("white", "Белый"),
                            ("oolong", "Улун"),
                            ("pu_erh", "Пуэр"),
                            ("yellow", "Желтый"),
                        ],
                        max_length=20,
                        verbose_name="Тип чая",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("china", "Китай"),
                            ("japan", "Япония"),
                            ("india", "Индия"),
                            ("sri_lanka", "Шри-Ланка"),
                            ("taiwan", "Тайвань"),
                            ("vietnam", "Вьетнам"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Страна происхождения",
                    ),
                ),
                (
                    "production_year",
                    models.PositiveIntegerField(verbose_name="Год производства"),
                ),
                (
                    "tea_grade",
                    models.CharField(
                        choices=[
                            ("special", "Особый"),
                            ("first", "Первый"),
                            ("second", "Второй"),
                            ("third", "Третий"),
                        ],
                        max_length=20,
                        verbose_name="Сорт чая",
                    ),
                ),
                ("appearance", models.TextField(verbose_name="Внешний вид")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tea_images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чай",
                "verbose_name_plural": "Чаи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeaComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст комментария")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Оценка от 1 до 5",
                        null=True,
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tea_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор комментария",
                    ),
                ),
                (
                    "tea_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tea_collection.teapost",
                        verbose_name="Чай",
                    ),
                ),
            ],
            options={
                "verbose_name": "комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ("created_at",),
            },
        ),
    ]
